image: silkeh/clang

stages:
  - test
  - build

before_script:
  - apt-get update -y

build_job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - fresh

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - cd tests
    - make
    - ./test
