image: gcc

stages:
  - test
  - build

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - ./liibft.h
      - ./libft.a

test:
  stage: test
  script:
    - make
    - cd tests
    - make
    - ./test
